services:
  lms-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
    image: lms-frontend:latest
    container_name: lms-frontend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3014
      - HOSTNAME=0.0.0.0
    ports:
      - "3014:3014"
