"use client";

import { useState } from "react";
import Link from "next/link";
import { resetPassword } from "@/lib/api/auth";

export default function ResetPasswordForm({ token }) {
  const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [success, setSuccess] = useState(false); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(e) { e.preventDefault(); setError(""); if (!token) return setError("This reset link is missing its token."); if (password.length < 12) return setError("Password must be at least 12 characters."); if (password !== confirm) return setError("Passwords do not match."); setBusy(true); try { await resetPassword(token, password); setSuccess(true); } catch (err) { setError(err.message || "This reset link is invalid or expired."); } finally { setBusy(false); } }
  return <main className="flex min-h-screen items-center justify-center bg-slate-50 px-6"><div className="w-full max-w-md rounded-2xl border border-slate-200 bg-white p-8 shadow-[var(--shadow-soft)]"><p className="text-xs font-semibold uppercase tracking-wider text-blue-600">Secure reset</p><h1 className="mt-2 text-2xl font-semibold text-slate-950">Choose a new password</h1>{success ? <><p className="mt-5 rounded-lg border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-700">Password reset successfully. Your old sessions have been invalidated.</p><Link href="/login" className="mt-5 inline-block font-semibold text-blue-600">Sign in</Link></> : <form onSubmit={submit} className="mt-6 space-y-4"><div><label className="mb-1 block text-sm font-medium">New password</label><input required minLength={12} type="password" value={password} onChange={(e) => setPassword(e.target.value)} className="h-11 w-full rounded-lg border border-slate-200 px-3"/><p className="mt-1 text-xs text-slate-400">At least 12 characters</p></div><div><label className="mb-1 block text-sm font-medium">Confirm password</label><input required minLength={12} type="password" value={confirm} onChange={(e) => setConfirm(e.target.value)} className="h-11 w-full rounded-lg border border-slate-200 px-3"/></div>{error && <p className="text-sm text-red-600">{error}</p>}<button disabled={busy || !token} className="h-11 w-full rounded-lg bg-blue-600 text-sm font-semibold text-white disabled:opacity-60">{busy ? "Resetting…" : "Reset password"}</button></form>}</div></main>;
}
